import type { CropConfig } from "../types";

export const CROP_CONFIGS = [
  {
    name: "Sunflower",
    label: "Sunflower",
    marketKey: "Sunflower",
    seedCostFlw: 0.01,
    harvestMinutes: 1,
  },
  {
    name: "Potato",
    label: "Potato",
    marketKey: "Potato",
    seedCostFlw: 0.1,
    harvestMinutes: 5,
  },
  {
    name: "Pumpkin",
    label: "Pumpkin",
    marketKey: "Pumpkin",
    seedCostFlw: 0.2,
    harvestMinutes: 30,
  },
  {
    name: "Carrot",
    label: "Carrot",
    marketKey: "Carrot",
    seedCostFlw: 0.5,
    harvestMinutes: 60,
  },
  {
    name: "Cabbage",
    label: "Cabbage",
    marketKey: "Cabbage",
    seedCostFlw: 1,
    harvestMinutes: 120,
  },
  {
    name: "Soybean",
    label: "Soybean",
    marketKey: "Soybean",
    seedCostFlw: 1.5,
    harvestMinutes: 180,
  },
  {
    name: "Beetroot",
    label: "Beetroot",
    marketKey: "Beetroot",
    seedCostFlw: 2,
    harvestMinutes: 240,
  },
  {
    name: "Cauliflower",
    label: "Cauliflower",
    marketKey: "Cauliflower",
    seedCostFlw: 3,
    harvestMinutes: 480,
  },
  {
    name: "Parsnip",
    label: "Parsnip",
    marketKey: "Parsnip",
    seedCostFlw: 5,
    harvestMinutes: 720,
  },
  {
    name: "Eggplant",
    label: "Eggplant",
    marketKey: "Eggplant",
    seedCostFlw: 6,
    harvestMinutes: 960,
  },
  {
    name: "Corn",
    label: "Corn",
    marketKey: "Corn",
    seedCostFlw: 7,
    harvestMinutes: 1200,
  },
  {
    name: "Radish",
    label: "Radish",
    marketKey: "Radish",
    seedCostFlw: 7,
    harvestMinutes: 1440,
  },
  {
    name: "Wheat",
    label: "Wheat",
    marketKey: "Wheat",
    seedCostFlw: 5,
    harvestMinutes: 1440,
  },
  {
    name: "Kale",
    label: "Kale",
    marketKey: "Kale",
    seedCostFlw: 7,
    harvestMinutes: 2160,
  },
  {
    name: "Barley",
    label: "Barley",
    marketKey: "Barley",
    seedCostFlw: 10,
    harvestMinutes: 2880,
  },
  {
    name: "Rhubarb",
    label: "Rhubarb",
    marketKey: "Rhubarb",
    seedCostFlw: 0.15,
    harvestMinutes: 10,
  },
  {
    name: "Zucchini",
    label: "Zucchini",
    marketKey: "Zucchini",
    seedCostFlw: 0.2,
    harvestMinutes: 30,
  },
  {
    name: "Yam",
    label: "Yam",
    marketKey: "Yam",
    seedCostFlw: 0.5,
    harvestMinutes: 60,
  },
  {
    name: "Broccoli",
    label: "Broccoli",
    marketKey: "Broccoli",
    seedCostFlw: 1,
    harvestMinutes: 120,
  },
  {
    name: "Pepper",
    label: "Pepper",
    marketKey: "Pepper",
    seedCostFlw: 2,
    harvestMinutes: 240,
  },
  {
    name: "Onion",
    label: "Onion",
    marketKey: "Onion",
    seedCostFlw: 7,
    harvestMinutes: 1200,
  },
  {
    name: "Turnip",
    label: "Turnip",
    marketKey: "Turnip",
    seedCostFlw: 5,
    harvestMinutes: 1440,
  },
  {
    name: "Artichoke",
    label: "Artichoke",
    marketKey: "Artichoke",
    seedCostFlw: 7,
    harvestMinutes: 2160,
  },
] as const satisfies readonly CropConfig[];

export const CROP_BY_NAME = Object.fromEntries(
  CROP_CONFIGS.map((crop) => [crop.name, crop]),
) as Record<CropConfig["name"], CropConfig>;
